import React, { useState, useEffect, useRef } from "react";
import { useTranslation } from "react-i18next";
import { useParams, useNavigate } from "react-router-dom";
import { MainLayout } from "../components/layout/Layout";
import {
  Card,
  Badge,
  Button,
  Spinner,
  Alert,
  Textarea,
} from "../components/ui";
import { patientService } from "../services/patientService";
import { appointmentService } from "../services/appointmentService";
import scannedPrescriptionService from "../services/scannedPrescriptionService";
import { getStatusLabel } from "../utils/helpers";
import { formatDateSafe } from "../utils/date/formatDateSafe";
import { debugLog, debugError } from "../utils/debug";
import FinancialManager from "../components/FinancialManager";
import {
  FileText,
  Upload,
  Camera,
  X,
  Eye,
  Download,
  Printer,
  Trash2,
  ZoomIn,
  ZoomOut,
  RotateCw,
  Copy,
} from "lucide-react";

/**
 * SecretaryPatientDetails - Display detailed view of a specific patient
 */
export const SecretaryPatientDetails = () => {
  const { t } = useTranslation();
  const { id: patientId } = useParams();
  const navigate = useNavigate();

  const [patient, setPatient] = useState(null);
  const [appointments, setAppointments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [scannedPrescriptions, setScannedPrescriptions] = useState([]);
  const [scannedLoading, setScannedLoading] = useState(false);
  const [scannedError, setScannedError] = useState("");
  const [selectedFile, setSelectedFile] = useState(null);
  const [fileNotes, setFileNotes] = useState("");
  const [uploadLoading, setUploadLoading] = useState(false);
  const [uploadError, setUploadError] = useState("");
  const [uploadSuccess, setUploadSuccess] = useState("");
  const [isDragOver, setIsDragOver] = useState(false);
  const [previewModal, setPreviewModal] = useState(null);
  const [imageZoom, setImageZoom] = useState(1);
  const [imageRotation, setImageRotation] = useState(0);
  const [panOffset, setPanOffset] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const [startX, setStartX] = useState(0);
  const [startY, setStartY] = useState(0);
  const fileInputRef = useRef(null);
  const containerRef = useRef(null);

  // Fetch patient details and appointments
  const fetchPatientDetails = async () => {
    setLoading(true);
    setError("");
    try {
      debugLog("SecretaryPatientDetails", "Fetching patient details", {
        patientId,
      });

      // Fetch all patients
      const patientsResponse = await patientService.getPatients();
      const patientsList = patientsResponse.data?.data || [];
      const foundPatient = patientsList.find((p) => p?._id === patientId);

      if (!foundPatient) {
        setError("Patient not found");
        return;
      }

      setPatient(foundPatient);

      // Fetch appointments and filter by patient
      const appointmentsResponse = await appointmentService.getAppointments();
      const appointmentsList = appointmentsResponse.data?.data || [];
      const patientAppointments = appointmentsList.filter(
        (app) => app?.patientId?._id === patientId,
      );

      setAppointments(patientAppointments);
    } catch (err) {
      console.error(err);
      const errorMsg =
        err.response?.data?.message ||
        err.message ||
        "Failed to fetch patient details";
      // Don't set error for 401s as they trigger logout automatically
      if (err.response?.status !== 401) {
        setError(errorMsg);
      }
      debugError("SecretaryPatientDetails", "Failed to fetch patient", err);
    } finally {
      setLoading(false);
    }
  };

  const fetchScannedPrescriptions = async () => {
    setScannedLoading(true);
    setScannedError("");
    try {
      const response =
        await scannedPrescriptionService.getPatientScannedPrescriptions(
          patientId,
        );
      setScannedPrescriptions(response.data?.data || []);
    } catch (err) {
      console.error(err);
      setScannedError(
        err.response?.data?.message ||
          err.message ||
          "Failed to load scanned prescriptions",
      );
    } finally {
      setScannedLoading(false);
    }
  };

  useEffect(() => {
    if (patientId) {
      fetchPatientDetails();
      fetchScannedPrescriptions();
    }
  }, [patientId]);

  useEffect(() => {
    if (imageZoom <= 1) {
      setIsDragging(false);
    }
  }, [imageZoom]);

  // Check if patient is provisioned (generated by secretary) or registered publicly
  const isProvisionedPatient = patient?.email?.endsWith("@mydoc90.local");
  const generatedPassword = isProvisionedPatient
    ? patient?.phoneNumber
      ? `Pt@${patient.phoneNumber}`
      : "—"
    : "كلمة مرور خاصة بالمريض (مسجل ذاتياً)";

  // Print function for scanned prescriptions
  const handlePrint = () => {
    window.print();
  };

  // Delete scanned prescription handler
  const handleDeletePrescription = async (prescriptionId) => {
    const confirmDelete = window.confirm(t("confirm_delete_prescription"));
    if (!confirmDelete) {
      return;
    }

    try {
      setUploadLoading(true);
      setUploadError("");
      await scannedPrescriptionService.deleteScannedPrescription(
        prescriptionId,
      );

      // Remove from local state
      setScannedPrescriptions(
        scannedPrescriptions.filter((p) => p._id !== prescriptionId),
      );

      setUploadSuccess(t("deleted_prescription_success"));
      setTimeout(() => setUploadSuccess(""), 3000);

      // Close preview if deleting currently previewed item
      if (previewModal?._id === prescriptionId) {
        setPreviewModal(null);
      }
    } catch (err) {
      console.error("Error deleting prescription:", err);
      setUploadError(
        err.response?.data?.message ||
          err.message ||
          t("delete_prescription_failed"),
      );
    } finally {
      setUploadLoading(false);
    }
  };

  const getDownloadUrl = (url) =>
    url?.includes("/upload/")
      ? url.replace("/upload/", "/upload/fl_attachment/")
      : url || "";

  const downloadUrl = getDownloadUrl(previewModal?.fileUrl);
  const isPdfPreview =
    previewModal?.fileType === "pdf" ||
    previewModal?.fileUrl?.toLowerCase().endsWith(".pdf");

  const handleZoomIn = () => setImageZoom((prev) => Math.min(prev + 0.25, 3));
  const handleZoomOut = () =>
    setImageZoom((prev) => Math.max(prev - 0.25, 0.5));
  const handleRotate = () => setImageRotation((prev) => (prev + 90) % 360);

  const resetPreviewState = () => {
    setImageZoom(1);
    setImageRotation(0);
    setPanOffset({ x: 0, y: 0 });
    setIsDragging(false);
    setStartX(0);
    setStartY(0);
  };

  const handleOpenPreview = (prescription) => {
    setPreviewModal(prescription);
    resetPreviewState();
  };

  const handleClosePreview = () => {
    setPreviewModal(null);
    resetPreviewState();
  };

  const handleImagePanMouseDown = (e) => {
    if (imageZoom <= 1) return;

    setIsDragging(true);
    setStartX(e.clientX - panOffset.x);
    setStartY(e.clientY - panOffset.y);
  };

  const handleImagePanMouseMove = (e) => {
    if (!isDragging) return;

    e.preventDefault();
    setPanOffset({ x: e.clientX - startX, y: e.clientY - startY });
  };

  const handleImagePanMouseUp = () => setIsDragging(false);
  const handleImagePanMouseLeave = () => setIsDragging(false);

  // Compress image if it's too large
  const compressImage = async (file) => {
    try {
      return await new Promise((resolve, reject) => {
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");
        const img = new Image();

        img.onload = () => {
          const maxWidth = 1920;
          const maxHeight = 1080;
          let { width, height } = img;

          if (width > maxWidth || height > maxHeight) {
            const ratio = Math.min(maxWidth / width, maxHeight / height);
            width *= ratio;
            height *= ratio;
          }

          canvas.width = width;
          canvas.height = height;
          ctx.drawImage(img, 0, 0, width, height);

          canvas.toBlob(
            (blob) => {
              if (blob) {
                resolve(blob);
              } else {
                reject(new Error("Image compression produced no blob"));
              }
            },
            "image/jpeg",
            0.8,
          );
        };

        img.onerror = (err) => reject(err);
        img.src = URL.createObjectURL(file);
      });
    } catch (err) {
      console.warn(
        "Image compression failed, falling back to the original file:",
        err,
      );
      return null;
    }
  };

  // Handle file selection
  const handleFileSelect = async (file) => {
    if (!file) return;

    const allowedTypes = ["image/jpeg", "image/png", "application/pdf"];
    if (!allowedTypes.includes(file.type)) {
      setUploadError("Only JPG, PNG, and PDF files are allowed");
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      if (file.type.startsWith("image/")) {
        const compressedBlob = await compressImage(file);
        if (
          compressedBlob &&
          compressedBlob.size &&
          compressedBlob.size < file.size
        ) {
          file = new File([compressedBlob], file.name, {
            type: "image/jpeg",
          });
        } else {
          console.warn(
            "Compression did not produce a smaller file or failed, using original file as fallback.",
          );
        }
      }
    }

    if (file.size > 5 * 1024 * 1024) {
      setUploadError("File size must be 5MB or less");
      return;
    }

    setSelectedFile(file);
    setUploadError("");
    setUploadSuccess("");
  };

  // Drag and drop handlers
  const handleDragOver = (e) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = (e) => {
    e.preventDefault();
    setIsDragOver(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragOver(false);

    const files = e.dataTransfer.files;
    if (files.length > 0) {
      handleFileSelect(files[0]);
    }
  };

  // Status badge colors (same as in other lists)
  const getStatusColor = (status) => {
    const normalizedStatus = String(status || "").toLowerCase();
    switch (normalizedStatus) {
      case "confirmed":
        return "success";
      case "pending":
        return "warning";
      case "cancelled":
        return "danger";
      case "reschedule_proposed":
        return "info";
      case "scheduled":
        return "primary";
      case "completed":
        return "secondary";
      default:
        return "default";
    }
  };

  if (loading) {
    return (
      <MainLayout userType="secretary">
        <div className="flex justify-center items-center min-h-96">
          <Spinner size="lg" />
        </div>
      </MainLayout>
    );
  }

  if (error) {
    return (
      <MainLayout userType="secretary">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <Alert type="error" message={error} />
          <div className="mt-6">
            <Button variant="secondary" onClick={() => navigate(-1)}>
              {t("pages_SecretaryPatientDetails.text_back")}
            </Button>
          </div>
        </div>
      </MainLayout>
    );
  }

  return (
    <MainLayout userType="secretary">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
                {t("patient_details")}: {patient?.name || "—"}
              </h1>
              <p className="text-gray-600 dark:text-gray-300 mt-2">
                {t("patient_details_sub")}
              </p>
            </div>
            <Button variant="secondary" onClick={() => navigate(-1)}>
              {t("back")}
            </Button>
          </div>
        </div>

        {/* Patient Info Card */}
        <Card className="mb-6">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
            <h3 className="text-lg font-medium text-gray-900 dark:text-white">
              {t("patient_info")}
            </h3>
          </div>
          <div className="px-6 py-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  {t("name")}
                </label>
                <p className="mt-1 text-sm text-gray-900 dark:text-white">
                  {patient?.name || "—"}
                </p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  {t("email")}
                </label>
                <p className="mt-1 text-sm text-gray-900 dark:text-white">
                  {patient?.email || "—"}
                </p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  {t("phone")}
                </label>
                <p className="mt-1 text-sm text-gray-900 dark:text-white">
                  {patient?.phoneNumber || t("not_provided")}
                </p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  {t("created_at")}
                </label>
                <p className="mt-1 text-sm text-gray-900 dark:text-white">
                  {formatDateSafe(patient?.createdAt)}
                </p>
              </div>
            </div>
          </div>
        </Card>

        {/* Patient credentials card */}
        <Card className="mb-6">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
            <h3 className="text-lg font-medium text-gray-900 dark:text-white">
              🔐 بيانات دخول بوابة المريض
            </h3>
          </div>
          <div className="px-6 py-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  البريد الإلكتروني
                </label>
                <div className="mt-1 flex items-center justify-between">
                  <div className="text-sm text-gray-900 dark:text-white">
                    {patient?.email || "—"}
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={async () => {
                      try {
                        await navigator.clipboard.writeText(
                          patient?.email || "",
                        );
                      } catch (e) {
                        console.error("Copy failed", e);
                      }
                    }}
                  >
                    <Copy className="w-4 h-4" /> نسخ
                  </Button>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  كلمة المرور الافتراضية
                </label>
                <div className="mt-1 flex items-center justify-between gap-4">
                  <div className="font-mono text-sm text-gray-900 dark:text-white">
                    {generatedPassword}
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    disabled={!isProvisionedPatient}
                    onClick={async () => {
                      if (!isProvisionedPatient) return;
                      try {
                        await navigator.clipboard.writeText(
                          generatedPassword === "—" ? "" : generatedPassword,
                        );
                      } catch (e) {
                        console.error("Copy failed", e);
                      }
                    }}
                  >
                    <Copy className="w-4 h-4" /> نسخ
                  </Button>
                </div>
              </div>
            </div>
            <p className="mt-3 text-xs text-gray-500 dark:text-gray-400">
              ملاحظة: كلمة المرور الافتراضية يتم إنشاؤها تلقائياً بناءً على رقم
              هاتف المريض المحفوظ.
            </p>
          </div>
        </Card>

        {/* Appointments Card */}
        <Card>
          <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
            <h3 className="text-lg font-medium text-gray-900 dark:text-white">
              {t("appointments")} ({appointments.length})
            </h3>
          </div>
          <div className="px-6 py-4">
            {appointments.length === 0 ? (
              <p className="text-sm text-gray-600 dark:text-gray-300">
                {t("no_appointments_for_patient")}
              </p>
            ) : (
              <div className="space-y-4">
                {appointments.map((appointment) => (
                  <div
                    key={appointment._id}
                    className="flex items-center justify-between p-4 border border-gray-200 dark:border-gray-700 rounded-lg"
                  >
                    <div className="flex-1">
                      <div className="flex items-center space-x-4">
                        <div>
                          <div className="font-medium text-gray-900 dark:text-white">
                            {formatDateSafe(appointment?.date)}
                          </div>
                          <div className="text-sm text-gray-500 dark:text-gray-400">
                            {appointment?.timeSlot || "—"}
                          </div>
                        </div>
                        <Badge variant={getStatusColor(appointment?.status)}>
                          {getStatusLabel(appointment?.status)}
                        </Badge>
                      </div>
                      {appointment?.notes && (
                        <div className="mt-2 text-sm text-gray-600 dark:text-gray-300">
                          {appointment.notes}
                        </div>
                      )}
                    </div>
                    <Button
                      variant="secondary"
                      size="sm"
                      onClick={() =>
                        navigate(`/secretary/appointments/${appointment._id}`)
                      }
                    >
                      {t("view_details")}
                    </Button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </Card>

        {/* Scanned Prescriptions Upload Card */}
        <Card className="mt-6">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
            <h3 className="text-lg font-medium text-gray-900 dark:text-white">
              {t("scanned_prescriptions")}
            </h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
              {t("scanned_prescriptions_help")}
            </p>
          </div>
          <div className="px-6 py-4 space-y-4">
            {uploadSuccess && (
              <Alert
                type="success"
                message={uploadSuccess}
                onClose={() => setUploadSuccess("")}
              />
            )}
            {uploadError && (
              <Alert
                type="danger"
                message={uploadError}
                onClose={() => setUploadError("")}
              />
            )}
            <form
              onSubmit={async (e) => {
                e.preventDefault();
                setUploadError("");
                setUploadSuccess("");

                if (!selectedFile) {
                  setUploadError(t("select_file_before_upload"));
                  return;
                }

                setUploadLoading(true);
                try {
                  await scannedPrescriptionService.uploadScannedPrescription(
                    patientId,
                    selectedFile,
                    fileNotes,
                  );
                  setUploadSuccess(t("upload_success"));
                  setSelectedFile(null);
                  setFileNotes("");
                  fetchScannedPrescriptions();
                } catch (err) {
                  console.error(err);
                  setUploadError(
                    err.response?.data?.message ||
                      err.message ||
                      t("upload_failed"),
                  );
                } finally {
                  setUploadLoading(false);
                }
              }}
              className="space-y-4"
            >
              {/* Drag and Drop Area */}
              <div
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                className={`relative border-2 border-dashed rounded-xl p-6 text-center transition-all duration-200 ${
                  isDragOver
                    ? "border-blue-400 bg-blue-50 dark:bg-blue-900/20"
                    : selectedFile
                      ? "border-green-400 bg-green-50 dark:bg-green-900/20"
                      : "border-gray-300 dark:border-gray-600 hover:border-gray-400 dark:hover:border-gray-500"
                }`}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".pdf,image/jpeg,image/png"
                  onChange={(event) => {
                    handleFileSelect(event.target.files?.[0] || null);
                  }}
                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-0"
                />

                <input
                  type="file"
                  accept="image/jpeg,image/png"
                  capture="environment"
                  style={{ display: "none" }}
                  id="camera-capture-input"
                  onChange={(event) => {
                    handleFileSelect(event.target.files?.[0] || null);
                  }}
                />

                <div className="space-y-2">
                  <Upload
                    className={`w-8 h-8 mx-auto ${isDragOver ? "text-blue-500" : "text-gray-400"}`}
                  />

                  <div>
                    <p className="text-sm font-medium text-gray-900 dark:text-white">
                      {isDragOver
                        ? t("drop_file_here")
                        : t("drag_drop_or_click")}
                    </p>
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                      {t("file_types_limit")}
                    </p>
                    <div className="mt-3">
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          const cam = document.getElementById(
                            "camera-capture-input",
                          );
                          if (cam) cam.click();
                        }}
                        className="relative z-10 inline-flex items-center gap-2 rounded-md bg-white dark:bg-slate-800 border border-gray-200 dark:border-gray-700 px-3 py-2 text-sm font-medium text-gray-800 dark:text-gray-100 hover:bg-gray-50 dark:hover:bg-slate-700 transition"
                      >
                        <Camera className="w-4 h-4" />
                        التقاط صورة بالكاميرا
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {/* File Preview */}
              {selectedFile && (
                <div className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                  <div className="flex items-center space-x-3">
                    <FileText className="w-5 h-5 text-gray-500" />
                    <div>
                      <p className="text-sm font-medium text-gray-900 dark:text-white">
                        {selectedFile.name}
                      </p>
                      <p className="text-xs text-gray-500">
                        {Math.round(selectedFile.size / 1024)}
                        {t("pages_SecretaryPatientDetails.text_kb")}
                      </p>
                    </div>
                  </div>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => setSelectedFile(null)}
                    className="text-red-500 hover:text-red-700"
                  >
                    <X className="w-4 h-4" />
                  </Button>
                </div>
              )}

              <Textarea
                label={t("prescription_notes_optional")}
                placeholder={t("prescription_notes_placeholder")}
                value={fileNotes}
                onChange={(e) => setFileNotes(e.target.value)}
                rows={3}
              />

              <Button
                type="submit"
                loading={uploadLoading}
                disabled={uploadLoading || !selectedFile}
                className="w-full"
              >
                {uploadLoading
                  ? t("uploading") || "Uploading..."
                  : t("upload_prescription") || "Upload prescription"}
              </Button>
            </form>

            <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
              <h4 className="text-md font-semibold text-gray-900 dark:text-white mb-3">
                {t("scanned_prescription_records")}
              </h4>
              {scannedLoading ? (
                <div className="flex justify-center py-8">
                  <Spinner size="lg" />
                </div>
              ) : scannedError ? (
                <Alert type="danger" message={scannedError} />
              ) : scannedPrescriptions.length === 0 ? (
                <p className="text-sm text-gray-600 dark:text-gray-300">
                  {t("no_scanned_prescriptions")}
                </p>
              ) : (
                <div className="space-y-4">
                  {scannedPrescriptions.map((prescription) => (
                    <div
                      key={prescription._id}
                      className="p-4 rounded-2xl bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 hover:shadow-md transition-shadow"
                    >
                      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                        <div className="flex items-center gap-3">
                          <div className="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg">
                            <FileText className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                          </div>
                          <div>
                            <p className="font-semibold text-gray-900 dark:text-white">
                              {prescription.fileType === "pdf"
                                ? t("prescription_pdf_file")
                                : t("prescription_image")}
                            </p>
                            <p className="text-sm text-gray-500 dark:text-gray-400">
                              {prescription.notes || t("no_notes")}
                            </p>
                            <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">
                              {prescription.uploadedAt
                                ? `${new Date(prescription.uploadedAt).toLocaleDateString("ar-EG", { calendar: "gregory", year: "numeric", month: "short", day: "numeric" })} ${new Date(prescription.uploadedAt).toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" })}`
                                : "-"}
                            </p>
                          </div>
                        </div>
                        <div className="flex gap-2">
                          <Button
                            variant="secondary"
                            size="sm"
                            onClick={() => handleOpenPreview(prescription)}
                            className="flex items-center gap-2"
                          >
                            <Eye className="w-4 h-4" />
                            {t("preview")}
                          </Button>
                          <a
                            href={getDownloadUrl(prescription.fileUrl)}
                            download={
                              prescription.fileType === "pdf"
                                ? "scanned-prescription.pdf"
                                : prescription.fileUrl?.split("/").pop()
                            }
                            target="_blank"
                            rel="noreferrer"
                            className="inline-flex items-center justify-center rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-100 dark:border-blue-800 dark:bg-blue-900/30 dark:text-blue-200 transition-colors"
                          >
                            <Download className="w-4 h-4 mr-2" />
                            {t("download")}
                          </a>
                          <Button
                            variant="danger"
                            size="sm"
                            onClick={() =>
                              handleDeletePrescription(prescription._id)
                            }
                            className="flex items-center gap-2"
                            disabled={uploadLoading}
                          >
                            <Trash2 className="w-4 h-4" />
                            {t("delete")}
                          </Button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </Card>

        {/* Financial Manager Card */}
        <Card className="mt-6">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
            <h3 className="text-lg font-medium text-gray-900 dark:text-white">
              {t("financial_plans")}
            </h3>
          </div>
          <div className="px-6 py-4">
            <FinancialManager patientId={patientId} />
          </div>
        </Card>
      </div>

      {/* Preview Modal */}
      {previewModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 overflow-y-auto"
          onClick={handleClosePreview}
        >
          <div
            className="relative w-full max-w-4xl h-[85vh] flex flex-col bg-slate-900 rounded-2xl overflow-hidden shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="h-14 bg-slate-800 text-white flex items-center justify-between px-6 border-b border-slate-700 font-medium z-10">
              <h3 className="text-lg font-semibold">
                {t("view_scanned_prescription")}
              </h3>
              <button
                type="button"
                aria-label={t("close")}
                onClick={handleClosePreview}
                className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-slate-700 text-white transition hover:bg-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-500"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div
              ref={containerRef}
              className={`flex-1 w-full h-full bg-slate-950 flex items-center justify-center overflow-hidden relative select-none ${isDragging ? "cursor-grabbing" : "cursor-grab"}`}
              onMouseDown={handleImagePanMouseDown}
              onMouseMove={handleImagePanMouseMove}
              onMouseUp={handleImagePanMouseUp}
              onMouseLeave={handleImagePanMouseLeave}
            >
              {isPdfPreview ? (
                <iframe
                  src={previewModal.fileUrl}
                  title={t(
                    "pages_SecretaryPatientDetails.attr_title_pdf_preview",
                  )}
                  className="max-w-full max-h-full w-auto h-auto rounded-2xl shadow-lg"
                />
              ) : (
                <img
                  src={previewModal.fileUrl}
                  alt={t(
                    "pages_SecretaryPatientDetails.attr_alt_scanned_prescription",
                  )}
                  className="max-w-full max-h-full rounded-2xl shadow-lg"
                  style={{
                    transform: `translate(${panOffset.x}px, ${panOffset.y}px) scale(${imageZoom}) rotate(${imageRotation}deg)`,
                    transition: isDragging
                      ? "none"
                      : "transform 0.15s ease-out",
                    maxHeight: "80vh",
                    maxWidth: "100%",
                    objectContain: "contain",
                    userSelect: "none",
                    pointerEvents: "auto",
                  }}
                />
              )}
            </div>

            <div className="sticky bottom-0 left-0 right-0 bg-slate-900/95 border-t border-slate-700 px-4 py-3 backdrop-blur-sm z-10">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex flex-wrap gap-2">
                  {!isPdfPreview && (
                    <>
                      <button
                        type="button"
                        onClick={handleZoomOut}
                        className="inline-flex items-center gap-2 rounded-full bg-slate-800 px-4 py-2 text-sm text-white transition hover:bg-slate-700"
                      >
                        <ZoomOut className="w-4 h-4" />
                        {t("zoom_out")}
                      </button>
                      <button
                        type="button"
                        onClick={handleZoomIn}
                        className="inline-flex items-center gap-2 rounded-full bg-slate-800 px-4 py-2 text-sm text-white transition hover:bg-slate-700"
                      >
                        <ZoomIn className="w-4 h-4" />
                        {t("zoom_in")}
                      </button>
                      <button
                        type="button"
                        onClick={handleRotate}
                        className="inline-flex items-center gap-2 rounded-full bg-slate-800 px-4 py-2 text-sm text-white transition hover:bg-slate-700"
                      >
                        <RotateCw className="w-4 h-4" />
                        {t("rotate")}
                      </button>
                    </>
                  )}
                </div>

                <a
                  href={downloadUrl || previewModal.fileUrl}
                  download={
                    previewModal.fileType === "pdf"
                      ? "scanned-prescription.pdf"
                      : previewModal.fileUrl?.split("/").pop()
                  }
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-blue-500"
                >
                  <Download className="w-4 h-4" />
                  {t("download_pdf")}
                </a>
              </div>
            </div>
          </div>
        </div>
      )}
    </MainLayout>
  );
};
